### ISSUE TITLE
Error in make min

### ISSUE THREAD

**Issue by friguzzi** [SWI-Prolog/swish#91]
I get
Tracing dependencies for: swish
Uglify file: /home/mlunife/swish/web/js/swish-min.js.new
Error: Cannot uglify file: /home/mlunife/swish/web/js/swish-min.js.new. Skipping it. Error is:
SyntaxError: Unexpected token punc «(», expected punc «:» (line: 2627, col: 11, pos: 206155)

Error
    at new JS_Parse_Error (/usr/local/lib/node_modules/requirejs/bin/r.js:15488:18)
    at js_error (/usr/local/lib/node_modules/requirejs/bin/r.js:15496:11)
    at croak (/usr/local/lib/node_modules/requirejs/bin/r.js:16035:9)
    at token_error (/usr/local/lib/node_modules/requirejs/bin/r.js:16043:9)
    at expect_token (/usr/local/lib/node_modules/requirejs/bin/r.js:16056:9)
    at expect (/usr/local/lib/node_modules/requirejs/bin/r.js:16059:36)
    at /usr/local/lib/node_modules/requirejs/bin/r.js:16632:13
    at /usr/local/lib/node_modules/requirejs/bin/r.js:16082:24
    at expr_atom (/usr/local/lib/node_modules/requirejs/bin/r.js:16562:35)
    at maybe_unary (/usr/local/lib/node_modules/requirejs/bin/r.js:16738:19)

/home/mlunife/swish/web/js/swish-min.js.new

**Comment by JanWielemaker** [comment]
Didn't read output carefully enough.  I get the same error.  It does seem to produce a working minified version.  It seems we need to upgrade the JavaScript tools we are using.  Bower is deprecated and the story around RequireJS is a bit unclear to me.   Some advice and input is needed ...

**Comment by friguzzi** [comment]
Unfortunately I have very little experience in Javascript...

**Comment by govi218** [comment]
The folks at Bower [seem to suggest](https://bower.io/blog/2017/how-to-migrate-away-from-bower/) Yarn as a viable replacement. I can set it up using this guide: https://itnext.io/bower-to-yarn-migration-simple-steps-2a5ad0c43281
FYI: more information on the landscape of JS package managers https://stackoverflow.com/questions/35062852/npm-vs-bower-vs-browserify-vs-gulp-vs-grunt-vs-webpack

**Comment by JanWielemaker** [comment]
Merged.  Closing.
